# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui//pythagoras.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmMain(object):
    def setupUi(self, frmMain):
        frmMain.setObjectName("frmMain")
        frmMain.resize(815, 489)
        self.slideAC = QtWidgets.QSlider(frmMain)
        self.slideAC.setGeometry(QtCore.QRect(240, 70, 21, 291))
        self.slideAC.setMaximum(1000)
        self.slideAC.setOrientation(QtCore.Qt.Vertical)
        self.slideAC.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.slideAC.setTickInterval(50)
        self.slideAC.setObjectName("slideAC")
        self.slideAB = QtWidgets.QSlider(frmMain)
        self.slideAB.setGeometry(QtCore.QRect(310, 400, 361, 21))
        self.slideAB.setMaximum(900)
        self.slideAB.setOrientation(QtCore.Qt.Horizontal)
        self.slideAB.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slideAB.setTickInterval(50)
        self.slideAB.setObjectName("slideAB")
        self.lblImageTriangle = QtWidgets.QLabel(frmMain)
        self.lblImageTriangle.setGeometry(QtCore.QRect(260, 20, 431, 371))
        self.lblImageTriangle.setText("")
        self.lblImageTriangle.setPixmap(QtGui.QPixmap(":/drawings/pythagoras.png"))
        self.lblImageTriangle.setScaledContents(True)
        self.lblImageTriangle.setObjectName("lblImageTriangle")
        self.label = QtWidgets.QLabel(frmMain)
        self.label.setGeometry(QtCore.QRect(550, 100, 251, 41))
        self.label.setStyleSheet("font: 75 14pt \"Noto Sans\";")
        self.label.setObjectName("label")
        self.lblAB = QtWidgets.QLabel(frmMain)
        self.lblAB.setGeometry(QtCore.QRect(460, 420, 58, 18))
        self.lblAB.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAB.setObjectName("lblAB")
        self.lblAC = QtWidgets.QLabel(frmMain)
        self.lblAC.setGeometry(QtCore.QRect(180, 190, 58, 18))
        self.lblAC.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAC.setObjectName("lblAC")
        self.lblPiet = QtWidgets.QLabel(frmMain)
        self.lblPiet.setGeometry(QtCore.QRect(20, 20, 151, 231))
        self.lblPiet.setText("")
        self.lblPiet.setPixmap(QtGui.QPixmap(":/drawings/piet.jpg"))
        self.lblPiet.setScaledContents(True)
        self.lblPiet.setObjectName("lblPiet")
        self.lblPythagoras = QtWidgets.QLabel(frmMain)
        self.lblPythagoras.setGeometry(QtCore.QRect(20, 30, 191, 261))
        self.lblPythagoras.setText("")
        self.lblPythagoras.setPixmap(QtGui.QPixmap(":/drawings/piet.png"))
        self.lblPythagoras.setScaledContents(True)
        self.lblPythagoras.setObjectName("lblPythagoras")

        self.retranslateUi(frmMain)
        QtCore.QMetaObject.connectSlotsByName(frmMain)

    def retranslateUi(self, frmMain):
        _translate = QtCore.QCoreApplication.translate
        frmMain.setWindowTitle(_translate("frmMain", "Pythagoras Theorem"))
        self.label.setText(_translate("frmMain", "Theorem = BC² = AB² + AC²"))
        self.lblAB.setText(_translate("frmMain", "0"))
        self.lblAC.setText(_translate("frmMain", "0"))
import images_rc
