# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui//pythagoras.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmMain(object):
    def setupUi(self, frmMain):
        frmMain.setObjectName("frmMain")
        frmMain.resize(645, 455)
        self.slideAC = QtWidgets.QSlider(frmMain)
        self.slideAC.setGeometry(QtCore.QRect(70, 50, 21, 291))
        self.slideAC.setMaximum(1000)
        self.slideAC.setOrientation(QtCore.Qt.Vertical)
        self.slideAC.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.slideAC.setTickInterval(50)
        self.slideAC.setObjectName("slideAC")
        self.slideAB = QtWidgets.QSlider(frmMain)
        self.slideAB.setGeometry(QtCore.QRect(140, 380, 361, 21))
        self.slideAB.setMaximum(900)
        self.slideAB.setOrientation(QtCore.Qt.Horizontal)
        self.slideAB.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slideAB.setTickInterval(50)
        self.slideAB.setObjectName("slideAB")
        self.lblImageTriangle = QtWidgets.QLabel(frmMain)
        self.lblImageTriangle.setGeometry(QtCore.QRect(90, 0, 431, 371))
        self.lblImageTriangle.setText("")
        self.lblImageTriangle.setPixmap(QtGui.QPixmap(":/drawings/pythagoras.png"))
        self.lblImageTriangle.setScaledContents(True)
        self.lblImageTriangle.setObjectName("lblImageTriangle")
        self.label = QtWidgets.QLabel(frmMain)
        self.label.setGeometry(QtCore.QRect(380, 80, 251, 41))
        self.label.setStyleSheet("font: 75 14pt \"Noto Sans\";")
        self.label.setObjectName("label")
        self.lblAB = QtWidgets.QLabel(frmMain)
        self.lblAB.setGeometry(QtCore.QRect(290, 400, 58, 18))
        self.lblAB.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAB.setObjectName("lblAB")
        self.lblAC = QtWidgets.QLabel(frmMain)
        self.lblAC.setGeometry(QtCore.QRect(10, 170, 58, 18))
        self.lblAC.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAC.setObjectName("lblAC")

        self.retranslateUi(frmMain)
        QtCore.QMetaObject.connectSlotsByName(frmMain)

    def retranslateUi(self, frmMain):
        _translate = QtCore.QCoreApplication.translate
        frmMain.setWindowTitle(_translate("frmMain", "Pythagoras Theorem"))
        self.label.setText(_translate("frmMain", "Theorem = BC² = AB² + AC²"))
        self.lblAB.setText(_translate("frmMain", "0"))
        self.lblAC.setText(_translate("frmMain", "0"))
import images_rc
