# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui//pythagoras.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmMain(object):
    def setupUi(self, frmMain):
        frmMain.setObjectName("frmMain")
        frmMain.resize(460, 399)
        self.buttonBox = QtWidgets.QDialogButtonBox(frmMain)
        self.buttonBox.setGeometry(QtCore.QRect(90, 350, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalSlider = QtWidgets.QSlider(frmMain)
        self.verticalSlider.setGeometry(QtCore.QRect(60, 30, 21, 291))
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.horizontalSlider = QtWidgets.QSlider(frmMain)
        self.horizontalSlider.setGeometry(QtCore.QRect(60, 320, 201, 21))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")

        self.retranslateUi(frmMain)
        self.buttonBox.accepted.connect(frmMain.accept)
        self.buttonBox.rejected.connect(frmMain.reject)
        QtCore.QMetaObject.connectSlotsByName(frmMain)

    def retranslateUi(self, frmMain):
        _translate = QtCore.QCoreApplication.translate
        frmMain.setWindowTitle(_translate("frmMain", "Pythagoras Theorem"))
